#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
findfile() {
	f=$ARCHIVE/$1
	test -r $f && return 0
	f=$HOME/Downloads/$1
	test -r $f || die "File not found [$f]"
}


test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

test -n "$MERIDIOVER" && \
	$dir/forwarder-test.sh chversion --dir=$tmp $MERIDIOVER

$XCLUSTER install_prog --dest=$tmp envsubst

if test "$__exconnect" = "multus"; then
	ovl_multus=$($XCLUSTER ovld multus)
	SETUP=None $ovl_multus/tar - | tar -C $tmp -x
fi

if test "$nsm_local" = "yes"; then
	nsmsh=$($XCLUSTER ovld nsm-ovs)/nsm-ovs.sh
	test -x $nsmsh || die "Not executable [$nsmsh]"
	log "Set NSM images :local"
	$nsmsh set_local_image \
		$tmp/etc/kubernetes/forwarder-test/nsc-template.yaml \
		$tmp/etc/kubernetes/forwarder-test/load-balancer-template.yaml \
		$tmp/etc/kubernetes/forwarder-test/nse-template.yaml
fi

findfile ctraffic.gz
zcat $f > $tmp/bin/ctraffic
chmod a+x $tmp/bin/ctraffic

birdd=$($dir/forwarder-test.sh bird_dir)
if test -x $birdd/bird; then
	log "Include bird routing suite"
	cp $birdd/bird $birdd/birdc $birdd/birdcl $tmp/bin
fi

if test "$__e2e" = "yes"; then
	log "Including Meridio e2e"
	d=$tmp/etc/kubernetes/meridio-e2e
	mkdir -p $d
	$dir/forwarder-test.sh generate_e2e --dest=$d 2> /dev/null || die
fi

test -n "$NFQLBD" || NFQLBD=$HOME/tmp/nfqlb
f=$NFQLBD/bin/ipu
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
