#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$

die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	setup_copied=yes
done
test "$setup_copied" != "yes" && test -d $dir/default && cp -R $dir/default/* $tmp

if test "$__auto_start" = "yes"; then
	destd=$tmp/etc/kubernetes/load
	srcd=$GOPATH/src/github.com/networkservicemesh/networkservicemesh/k8s/conf
	mkdir -p $tmp/etc/kubernetes/load
	export CA_BUNDLE='""'
	for f in namespace-nsm.yaml admission-webhook.yaml \
		admission-webhook-cfg.yaml cluster-role-admin.yaml \
		cluster-role-binding.yaml cluster-role-view.yaml \
		crd-networkserviceendpoints.yaml crd-networkservicemanagers.yaml \
		crd-networkservices.yaml nsmgr.yaml \
		; do

		test -r $srcd/$f || die "Not readable [$srcd/$f]"
		envsubst < $srcd/$f > $destd/$f
	done
fi

f=$GOPATH/bin/dpframework
test -x $f && cp $f $tmp/bin
f=$GOPATH/src/github.com/Nordix/dpframework/scripts/fakedev
test -x $f && cp $f $tmp/bin

d=$GOPATH/src/github.com/networkservicemesh/examples/examples/bridge-domain
test -d "$d/k8s" && cp -r "$d/k8s" $tmp/etc/kubernetes/bridge-domain

d=$GOPATH/src/github.com/Nordix/nsm-forwarder-generic
for f in forwarder-generic.yaml forwarder-kernel.yaml forwarder-generic-vlan.yaml forwarder-vlan.yaml; do
	 test -r $d/$f && cp $d/$f $tmp/etc/kubernetes/nsm-next-gen
done


d=$GOPATH/src/github.com/Nordix/nsm-nse-generic
f=nse-generic.yaml
test -r $d/$f && cp $d/$f $tmp/etc/kubernetes/nsm-next-gen

if test -n $XCLUSTER_INSTALL_MULTUS; then
       if [ ! -d $XCLUSTER_WORKSPACE/multus-cni ]; then
               log "Clone multus-cni to $XCLUSTER_WORKSPACE/multus-cni"
               git clone https://github.com/k8snetworkplumbingwg/multus-cni.git $XCLUSTER_WORKSPACE/multus-cni/
       fi

       if [ ! -d $XCLUSTER_WORKSPACE/cni-plugins ]; then
               log "Clone cni-plugins to $XCLUSTER_WORKSPACE/cni-plugins"
               git clone https://github.com/containernetworking/plugins $XCLUSTER_WORKSPACE/cni-plugins/
               cd $XCLUSTER_WORKSPACE/cni-plugins/
               git checkout v0.8.7
               log "Build CNI plugins v0.8.7"
               ./build_linux.sh
               cd -
       fi

       log "Copy multus-cni to $tmp/etc/kubernetes/"
       test -d $XCLUSTER_WORKSPACE/multus-cni && cp -r $XCLUSTER_WORKSPACE/multus-cni $tmp/etc/kubernetes/
       log "Copy CNI plugins to $tmp/opt/cni/bin"
       test -f $XCLUSTER_WORKSPACE/cni-plugins/bin/vlan && mkdir -p $tmp/opt/cni/bin && cp $XCLUSTER_WORKSPACE/cni-plugins/bin/vlan $tmp/opt/cni/bin/
       test -f $XCLUSTER_WORKSPACE/cni-plugins/bin/static && mkdir -p $tmp/opt/cni/bin && cp $XCLUSTER_WORKSPACE/cni-plugins/bin/static $tmp/opt/cni/bin/
       #test -d $XCLUSTER_WORKSPACE/cni-plugins/bin && mkdir -p $tmp/opt/cni/bin && cp $XCLUSTER_WORKSPACE/cni-plugins/bin/* $tmp/opt/cni/bin/
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp

