apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: meridio-black
spec:
  config: '{
    "cniVersion": "0.4.0",
    "type": "bridge",
    "bridge": "mbr1",
    "ipam": {
      "type": "dhcp"
    }
  }'
