---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse
  labels:
    app: nse
spec:
  selector:
    matchLabels:
      app: nse
  template:
    metadata:
      labels:
        app: nse
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm-004
      containers:
        - name: nse
          image: registry.nordix.org/cloud-native/nsm/cmd-nse-vlan:vlansup
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
              hostPort: 5003
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_CONNECT_TO
              value: "nsm-registry-svc:5002"
            - name: NSM_SERVICES
              value: "finance-bridge { vlan: 100; via: gw1}"
            - name: NSM_CIDR_PREFIX
              value: "172.10.0.0/24"
            - name: NSM_IPV6_PREFIX
              value: "100:200::/64"
            - name: NSM_POINT2POINT
              value: "False"
            - name: NSM_LISTEN_ON
              value: "tcp://:5003"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
