---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse
  labels:
    app: nse
spec:
  selector:
    matchLabels:
      app: nse
  template:
    metadata:
      labels:
        app: nse
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm-003
      containers:
        - name: nse
          image: registry.nordix.org/cloud-native/nsm/nse-generic:vlan-0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSE_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSE_SERVICE_NAME
              value: "icmp-responder"
            - name: NSE_CIDR_PREFIX
              value: "169.254.0.0/24"
            - name:  NSE_POINT2POINT
              value: "False"
            - name: NSE_VLAN_BASE_IFNAME
              value: "eth2"
            - name: NSE_VLAN_ID
              value: "100"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
