apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: forwarder-ovs
  name: forwarder-ovs
spec:
  selector:
    matchLabels:
      app: forwarder-ovs
  template:
    metadata:
      labels:
        app: forwarder-ovs
    spec:
      containers:
      - env:
        - name: NSM_L2_RESOURCE_SELECTOR_FILE
          value: /etc/nsm/DomainConfigFileOvs
        - name: NSM_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_CONNECT_TO
          value: unix:///var/lib/networkservicemesh/nsm.io.sock
        - name: NSM_LOG_LEVEL
          value: TRACE
        - name: NSM_SRIOV_CONFIG_FILE
          value: /var/lib/networkservicemesh/smartnic.config
        - name: NSM_BRIDGE_NAME
          value: br-nsm
        - name: NSM_TUNNEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: ghcr.io/networkservicemesh/cmd-forwarder-ovs:v1.4.0
        imagePullPolicy: IfNotPresent
        name: forwarder-ovs
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/spire/sockets
          name: spire-agent-socket
          readOnly: true
        - mountPath: /var/lib/networkservicemesh
          name: nsm
        - mountPath: /var/lib/kubelet
          name: kubelet-socket
        - mountPath: /host/sys/fs/cgroup
          name: cgroup
        - mountPath: /host/dev/vfio
          name: vfio
        - mountPath: /var/run/openvswitch
          name: ovs-socket
          readOnly: true
        - name: nsm-config
          mountPath: /etc/nsm
      hostNetwork: true
      hostPID: true
      volumes:
      - hostPath:
          path: /run/spire/sockets
          type: Directory
        name: spire-agent-socket
      - hostPath:
          path: /var/lib/networkservicemesh
          type: Directory
        name: nsm
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-socket
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - hostPath:
          path: /dev/vfio
          type: DirectoryOrCreate
        name: vfio
      - hostPath:
          path: /usr/local/var/run/openvswitch
          type: DirectoryOrCreate
        name: ovs-socket
      - name: nsm-config
        hostPath:
          path: /etc/nsm/
          type: DirectoryOrCreate
