apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nsc-network2
  name: nsc-network2
spec:
  selector:
    matchLabels:
      app: nsc-network2
  replicas: 3
  template:
    metadata:
      labels:
        app: nsc-network2
    spec:
      containers:
      - env:
        - name: NSM_NETWORK_SERVICES
          value: kernel://network2/nsm-1
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_LOG_LEVEL
          value: TRACE
        - name: NSM_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/networkservicemesh/cmd-nsc:v1.2.0
        imagePullPolicy: IfNotPresent
        name: nsc
        volumeMounts:
        - mountPath: /run/spire/sockets
          name: spire-agent-socket
          readOnly: true
        - mountPath: /var/lib/networkservicemesh
          name: nsm-socket
          readOnly: true
      volumes:
      - hostPath:
          path: /run/spire/sockets
          type: Directory
        name: spire-agent-socket
      - hostPath:
          path: /var/lib/networkservicemesh
          type: DirectoryOrCreate
        name: nsm-socket
