apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nse-remote-vlan
  name: nse-remote-vlan
spec:
  selector:
    matchLabels:
      app: nse-remote-vlan
  template:
    metadata:
      labels:
        app: nse-remote-vlan
        spiffe.io/spiffe-id: "true"
    spec:
      containers:
      - env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NSM_CONNECT_TO
          value: nsm-registry:5002
        - name: NSM_SERVICES
          value: 'finance-bridge { vlan: 100; via: service.domain.2}'
# NSM > v1.3.x
        - name: NSM_CIDR_PREFIX
          value: "169.254.100.0/24,100:100::/64"
# NSM <= v1.3.x
#        - name: NSM_CIDR_PREFIX
#          value: "169.254.100.0/24"
#        - name: NSM_IPV6_PREFIX
#          value: "100:100::/64"
        - name: NSM_POINT2POINT
          value: "True"
        - name: NSM_REGISTER_SERVICE
          value: "True"
        - name: NSM_LISTEN_ON
          value: tcp://:5003
        image: ghcr.io/networkservicemesh/cmd-nse-remote-vlan:v1.4.0-rc.2
        imagePullPolicy: IfNotPresent
        name: nse
        ports:
        - containerPort: 5003
          hostPort: 5003
        volumeMounts:
        - mountPath: /run/spire/sockets
          name: spire-agent-socket
          readOnly: true
        - mountPath: /var/lib/networkservicemesh
          name: nsm-socket
          readOnly: false
      volumes:
      - hostPath:
          path: /run/spire/sockets
          type: Directory
        name: spire-agent-socket
      - hostPath:
          path: /var/lib/networkservicemesh
          type: DirectoryOrCreate
        name: nsm-socket
