apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nse-network2
  name: nse-network2
spec:
  selector:
    matchLabels:
      app: nse-network2
  template:
    metadata:
      labels:
        app: nse-network2
    spec:
      containers:
      - env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        - name: NSM_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NSM_CONNECT_TO
          value: nsm-registry.default:5002
        - name: NSM_SERVICES
          value: 'network2 { vlan: 200; via: eth2}'
        - name: NSM_CIDR_PREFIX
          value: "169.254.102.0/24,100:102::/64"
        - name: NSM_POINT2POINT
          value: "False"
        - name: NSM_REGISTER_SERVICE
          value: "True"
        - name: NSM_LISTEN_ON
          value: tcp://:5003
        image: ghcr.io/networkservicemesh/cmd-nse-remote-vlan:v1.7.1
        imagePullPolicy: IfNotPresent
        name: nse
        ports:
        - containerPort: 5003
          hostPort: 5003
        volumeMounts:
        - mountPath: /run/spire/sockets
          name: spire-agent-socket
          readOnly: true
        - mountPath: /var/lib/networkservicemesh
          name: nsm-socket
          readOnly: false
      volumes:
      - hostPath:
          path: /run/spire/sockets
          type: Directory
        name: spire-agent-socket
      - hostPath:
          path: /var/lib/networkservicemesh
          type: DirectoryOrCreate
        name: nsm-socket
