---
# Source: nsm/templates/nsmgr.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nsmgr
  labels:
    app: nsmgr
spec:
  selector:
    matchLabels:
      app: nsmgr
  template:
    metadata:
      labels:
        app: nsmgr
    spec:
      containers:
        - name: nsmgr
          image: registry.nordix.org/cloud-native/nsm/cmd-nsmgr:vlansup
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
              hostPort: 5001
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_REGISTRY_URL
              value: "nsm-registry-svc:5002"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NSM_LISTEN_ON
              value: unix:///var/lib/networkservicemesh/nsm.io.sock,tcp://:5001
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: xcluster
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
---
# Source: nsm/templates/registry-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nsm-registry-svc
spec:
  selector:
    app: nsm-registry
  ports:
    - name: nsm-registry-svc
      protocol: TCP
      port: 5002
      targetPort: 5002
---
# Source: nsm/templates/registry-memory.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsm-registry
  labels:
    app: nsm-registry
spec:
  selector:
    matchLabels:
      app: nsm-registry
  template:
    metadata:
      labels:
        app: nsm-registry
    spec:
      containers:
        - name: nsm-registry
          image: registry.nordix.org/cloud-native/nsm/cmd-registry-memory:vlansup
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: REGISTRY_MEMORY_LISTEN_ON
              value: tcp://:5002
            - name: REGISTRY_MEMORY_PROXY_REGISTRY_URL
              value: nsm-registry-proxy-dns-svc:5003
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
              hostPort: 5002
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
